services:
  server:
    build:
      context: .
      # develop:
      #   watch:
      #     - action: sync
      #       path: .
      #       target: .
      #       ignore:
      #         - node_modules/
      #     - action: rebuild
      #       path: package.json
    environment:
      NODE_ENV: production
      DATABASE_URL: ${DATABASE_URL}
      CLERK_SECRET_KEY: ${CLERK_SECRET_KEY}
      CLIENT_URL: ${CLIENT_URL}
      AWS_ACCESS_ID: ${AWS_ACCESS_ID}
      AWS_SECRET_KEY: ${AWS_SECRET_KEY}
      AWS_S3_REGION: ${AWS_S3_REGION}
      BUCKET_NAME: ${BUCKET_NAME}
    ports:
      - 7635:7635
  db:
    image: mongo
    ports:
      - 5432:5432
    environment:
      DATABASE_URL: mongodb+srv://wirayuda233:iwEI8qDsbMPLgcaY@snaply-mongo.vl7kxe8.mongodb.net/snaply?retryWrites=true&w=majority
